# Generated by Django 3.2.9 on 2023-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20230507_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=150)),
            ],
        ),
    ]
