# Generated by Django 3.2.9 on 2023-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
