# Generated by Django 3.2.9 on 2023-05-10 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230510_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateAdded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
