# Generated by Django 4.2.1 on 2023-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
    ]
